services:
  web:
    image: "ella0110/trillobackend:20241005.3"
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      sqlserver: 
        condition: service_healthy
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=@Aa12345678
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-C", "-S", "localhost", "-U", "sa", "-P", "@Aa12345678", "-Q", "SELECT 1", "-b", "-o", "/dev/null"]
      # test: /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P ${MSSQL_SA_PASSWORD} -Q 'SELECT 1' -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
