services:
  web:
    image: "ella0110/trillobackend:20250115.10"
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      db: 
        condition: service_healthy
  db:
    image: postgres
    environment:
      - POSTGRES_DB=trillo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=@Aa12345678
      - PGUSER=postgres
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "trillo"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s